### ISSUE TITLE
Issues with Crystal 0.33.0

### ISSUE THREAD

**Issue by jwoertink** [maiha/memoized.cr#3]
https://github.com/maiha/memoized.cr/blob/c053bcf2dcc97f7dd7744f2376231ab4c4feb135/src/memoized/policy.cr#L13

`Time.now` is no longer a method in Crystal 0.33.0

**Comment by maiha** [comment]
@jwoertink Thanks for your report. 
I bumped version to `0.9.0` that now supports crystal-0.33.0 too.
Please give it a try.
